#!/usr/bin/python3

''' this script uses SQLAlchemy ORM to cretae table like classes '''

import MySQLdb
import sys
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base


db_query = 'mysql+mysqldb:;//{}:{}@localhost:3306/{}'
engine = create_engine(db_query.format(sys.argv[1], sys.argv[2], sys.argv[3]))
Session = sessionmaker(bind=engine)
session = Session()

Base = declarative_base()


class State(Base):
    ''' this class defines all state objects '''

    __tablename__ = 'states'

    id = Column(Integer, Unique=True, autoincrement=True, nullable=True,
            primary_key=True)
    name = Column(String(128), nullable=False)


Base.metadata.create_all(engine)
